# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90d18105bea607f5e6352d974bde749e941a1c1554d582e22fee3234d32bdf188d2c611cd9b40295ea1b3cf3f15306c79f45b11968fb5707d463eedfaebb254b

test:
  secret_key_base: d31a9580ddd6e0131ea3652bdbb1209ff01210e0947b8230fac5583c17e6ed6d4f075fc7403cb453adcece5e06ddcb3e7c0dfc83bfcb69b7fb86a0c3624805c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
